apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: mcp-outline
  app.kubernetes.io/part-of: mcp-outline

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
